# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Sistemas Paralelos e Distribuídos 2021-2022
author: Margarida Madeira e Moura
logo: images/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex


# Information about where the book exists on the web
repository:
  url: https://github.com/margaridamadeira/SPDis-2021-22  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: false
  home_page_in_navbar         : false
  baseurl                     : https://margaridamadeira.github.io/SPDis-2021-22/

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

latex:
  latex_engine                : xelatex
  latex_documents:
    targetname: SPDis.tex
  # use_jupyterbook_latex: false

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - html_admonition
    # - deflist
    - dollarmath
    - html_image
    - linkify
    # - replacements
    # - smartquotes
    - substitution

# #######################################################################################
# sphinx 
sphinx:
  config:
    language: pt
    bibtex_reference_style: label
    